### PR TITLE
2021 dataset update

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by blokhin** [comment]
ESPResSo = Quantum ESPRESSO, right?

**Comment by ltalirz** [comment]
> ESPResSo = Quantum ESPRESSO, right?

No, that's the classical MD code, just have a look at https://atomistic.software/

The search results in this particular case do have a few false positives though that would need to be investigated; I've added it to the to-do list

**Comment by ltalirz** [comment]
In case anyone arrives here, looking for the 2021 update:

The reason I haven't merged this pull request yet: while the 2021 data for most codes follows pre-existing trends, there appears to be an anomaly in the citation data for Gaussian, with the values for 2021 ([8770](https://scholar.google.com/scholar?q=Frisch%20%22Gaussian%2070%22%20OR%20%22Gaussian%2076%22%20OR%20%22Gaussian%2080%22%20OR%20%22Gaussian%2082%22%20OR%20%22Gaussian%2086%22%20OR%20%22Gaussian%2088%22%20OR%20%22Gaussian%2090%22%20OR%20%22Gaussian%2092%22%20OR%20%22Gaussian%2094%22%20OR%20%22Gaussian%2098%22%20OR%20%22Gaussian%2003%22%20OR%20%22Gaussian%2009%22%20OR%20%22Gaussian%2016%22&hl=en&as_sdt=0%2C5&as_ylo=2021&as_yhi=2021)) being substantially lower than the ones for 2020 (13'200).

I checked that the 2020 citation counts for Gaussian are unchanged (<1%) since the last data query, so Google Scholar is really reporting a radical deviation from the trend in 2021 - which could be possible but would seem rather surprising.

I'll postpone this update for one more week and check the results again.

**Comment by ltalirz** [comment]
Turns out the data didn't change yet. Will commit & push, while keeping 2020 the default display year for the table for the time being.

**Pull request merged**
